name: Common Models

on:
  push:
    branches: [ master ]
    paths: 
      - 'Common.Models/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_and_deploy:
    uses: ./.github/workflows/shared.yml
    with:
      project_file: Common.Models.csproj
      project_folder: Common.Models
    secrets:
      nuget_api_key: ${{secrets.NUGET_API_KEY}}

  