name: Common Models
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: "3.1"
  PROJECT_FILE: Common.Models.csproj
  PROJECT_FOLDER: ./Common.Models

on:
  push:
    branches: [ master ]
    paths: 
      - 'Common.Models/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Tool for Version
        run: dotnet tool install -g dotnet-version-cli

      - name: Git config
        run: |
            git config --local user.email "github@fluentchange.com"
            git config --local user.name "FluentChange GitHub"   

      - name: Increment version
        working-directory: ${{ env.PROJECT_FOLDER }}
        run: dotnet version -m "Auto increment version to v\$newVer by CI/CD pipeline" patch

      - name: Install dependencies
        run: dotnet restore FluentChange.Extensions.sln

      - name: Build
        run: dotnet build FluentChange.Extensions.sln --configuration Release --restore

      - name: Pack & push nuget
        working-directory: ${{ env.PROJECT_FOLDER }}
        run: |
            dotnet pack ${{ env.PROJECT_FILE }} --configuration Release
            dotnet nuget push bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Git push changes back to repo
        run: |
            git push
            git push --tags