name: CI
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION_1: "3.1"
  DOTNET_VERSION_2: "5.0"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION_1 }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION_1 }}

      - name: Setup Dotnet ${{ env.DOTNET_VERSION_2 }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION_2 }}
            
      - name: Install dependencies
        run: dotnet restore FluentChange.Extensions.sln
      
      - name: Build
        run: dotnet build FluentChange.Extensions.sln --configuration Release --no-restore

      - name: Pack nuget AzureFunctions
        working-directory: ./Azure.Functions
        run: dotnet pack Azure.Functions.csproj --configuration Release --no-build --no-restore 

      - name: Pack nuget Common.Database
        working-directory: ./Common.Database
        run: dotnet pack Common.Database.csproj --configuration Release --no-build --no-restore 

      - name: Pack nuget Common.Rest
        working-directory: ./Common.Rest
        run: dotnet pack Common.Rest.csproj --configuration Release --no-build --no-restore 

      - name: Pack nuget Common.Models
        working-directory: ./Common.Models
        run: dotnet pack Common.Models.csproj --configuration Release --no-build --no-restore 

      - name: Pack nuget Blazor
        working-directory: ./Blazor
        run: dotnet pack Blazor.csproj --configuration Release --no-build --no-restore 

      - name: Pack nuget System
        working-directory: ./System
        run: dotnet pack System.csproj --configuration Release --no-build --no-restore 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            ./Azure.Functions/bin/Release/
            ./Common.Database/bin/Release/
            ./Common.Rest/bin/Release/
            ./Common.Models/bin/Release/
            ./Blazor/bin/Release/
            ./System/bin/Release/


  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: nuget
          path: nuget
      
      - name: Push nuget
        run: dotnet nuget push nuget/**/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
